management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: env,info,health

greeting:
  name: Max
  coffee: ${greeting.name} is drinking Coffee Cereza


droid:
  id: BB-8
  description: Small, rolling android. Probaly doesn't drink coffee.

